### ISSUE TITLE
Errors during installations

### ISSUE THREAD

**Issue by AlABarazi** [zenodo/zenodo-rdm#1053]
Hi, 
Have anyone tried/tested/installed  this before ? It seems that the pipfile is not formated correctly and it has multiple issues.
In pipfile there is this line 
zenodo_rdm = {editable="True", path="./site"}
it seems it is wrong and it should be editable=true.

The readme says "See the [InvenioRDM Documentation](https://inveniordm.docs.cern.ch/install/) for further installation options."
What is meant by "the further installation options?" This is vague.

After fixing this another error appear

```
➜  zenodo-rdm git:(master) ✗ invenio-cli install
Locking python dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠧ Locking packages...False
<console width=110 ColorSystem.TRUECOLOR>
Traceback (most recent call last):
  File "/Users/alaaalbarazi/Library/Python/3.9/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/cli/options.py", line 52, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/vendor/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/cli/command.py", line 342, in lock
    do_lock(
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/routines/lock.py", line 67, in do_lock
    venv_resolve_deps(
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/utils/resolver.py", line 907, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
  File "/Users/alaaalbarazi/Library/Python/3.9/lib/python/site-packages/pipenv/utils/resolver.py", line 771, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!
Failed to install dependencies.
```

**Comment by slint** [comment]
Similar to #1120, this shouldn't be an issue anymore, `uv` is much more reliable in installing the right dependencies for local development.
